name: DamageIndicator
main: cl.mastercode.DamageIndicator.DIMain
author: CristianDossow
authors: [ Beelzebu, Kua_ ]
version: ${project.version}
softdepend: [ ProtocolLib ]
api-version: 1.16
commands:
  damageindicator:
    description: Main DamageIndicator command
    usage: /<command> <arguments>
    aliases: [ di ]
permissions:
  damageindicator.admin:
    description: Access to admin commands
